; Assembly code generated by compiler
	global main
	extern printf, malloc                ; C functions
	extern make_closure, call_closure    ; built-in functions
	extern plus, minus, equals           ; standard library functions

	section .text
_f0:
	push rbp
	mov rbp, rsp
	sub rsp, 40        ; memory for local variables
	mov rax, rdi       ; pointer to vector of arguments
	mov rbx, QWORD [rax+0]    ; move x from heap
	mov QWORD [rbp-8], rbx    ; move x to stack
	mov rax, 1                ; integer constant
	mov QWORD [rbp-16], rax    ; preparing operand 2/2
	mov rax, QWORD [rbp-8]    ; access x
	mov QWORD [rbp-24], rax    ; preparing operand 1/2
	mov rax, plus            ; access plus
	mov QWORD [rbp-32], rax    ; preparing closure
	mov rdx, QWORD [rbp-16]    ; operand 2/2
	mov rsi, QWORD [rbp-24]    ; operand 1/2
	mov rdi, QWORD [rbp-32]    ; operator location
	call call_closure            ; output goes to rax
	leave
	ret
main:
	push rbp
	mov rbp, rsp
	sub rsp, 32        ; memory for local variables
	mov rdx, 0            ; number of free variables
	mov rsi, 1            ; number of bound variables
	mov rdi, _f0            ; name of function
	call make_closure
	mov QWORD [rbp-8], rax    ; let inc
	mov rax, 1                ; integer constant
	mov QWORD [rbp-16], rax    ; preparing operand 1/1
	mov rax, QWORD [rbp-8]    ; access inc
	mov QWORD [rbp-24], rax    ; preparing closure
	mov rsi, QWORD [rbp-16]    ; operand 1/1
	mov rdi, QWORD [rbp-24]    ; operator location
	call call_closure            ; output goes to rax
	mov rsi, rax        ; will print rax
	mov rdi, message
	mov rax, 0
	call printf
	mov rax, 0            ; exit code 0
	leave
	ret

	section .data
message: db "%d", 10, 0        ; 10 is newline, 0 is end-of-string
